### ISSUE TITLE
Compiler warnings (default level at Arduino IDE)

### ISSUE THREAD

**Issue by NickNifontov** [charlesbaynham/OSFS#1]
`

sketch\LeOS_EEPROM.cpp: In function 'void OSFS::readNBytes(uint16_t, unsigned int, void*)':

sketch\LeOS_EEPROM.cpp:45:11: warning: ISO C++ forbids incrementing a pointer of type 'void*' [-Wpointer-arith]

     output++;

           ^

sketch\LeOS_EEPROM.cpp: In function 'void OSFS::writeNBytes(uint16_t, unsigned int, const void*)':

sketch\LeOS_EEPROM.cpp:53:10: warning: ISO C++ forbids incrementing a pointer of type 'const void*' [-Wpointer-arith]

     input++;

          ^

In file included from sketch\LeOS_EEPROM.cpp:5:0:

sketch\OSFS.h: In instantiation of 'OSFS::result OSFS::getFile(const char*, T&) [with T = int]':

sketch\LeOS_EEPROM.cpp:274:34:   required from here

sketch\OSFS.h:121:23: warning: 'readNBytesChk' was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]

   return readNBytesChk(add, size, &buf);

                       ^

sketch\OSFS.h:230:9: note: 'OSFS::result OSFS::readNBytesChk(uint16_t, unsigned int, void*)' declared here, later in the translation unit

  result readNBytesChk(uint16_t address, unsigned int num, void* input);

         ^

sketch\OSFS.h: In instantiation of 'OSFS::result OSFS::getFile(const char*, T&) [with T = long int]':

sketch\LeOS_EEPROM.cpp:275:44:   required from here

sketch\OSFS.h:121:23: warning: 'readNBytesChk' was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]

   return readNBytesChk(add, size, &buf);

                       ^

sketch\OSFS.h:230:9: note: 'OSFS::result OSFS::readNBytesChk(uint16_t, unsigned int, void*)' declared here, later in the translation unit

  result readNBytesChk(uint16_t address, unsigned int num, void* input);

         ^

sketch\OSFS.h: In instantiation of 'OSFS::result OSFS::getFile(const char*, T&) [with T = long unsigned int]':

sketch\LeOS_EEPROM.cpp:304:53:   required from here

sketch\OSFS.h:121:23: warning: 'readNBytesChk' was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]

   return readNBytesChk(add, size, &buf);

                       ^

sketch\OSFS.h:230:9: note: 'OSFS::result OSFS::readNBytesChk(uint16_t, unsigned int, void*)' declared here, later in the translation unit

  result readNBytesChk(uint16_t address, unsigned int num, void* input);

         ^

sketch\OSFS.h: In instantiation of 'OSFS::result OSFS::getFile(const char*, T&) [with T = _LeOS_DATA_EEPROM]':

sketch\LeOS_EEPROM.cpp:357:38:   required from here

sketch\OSFS.h:121:23: warning: 'readNBytesChk' was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]

   return readNBytesChk(add, size, &buf);

                       ^

sketch\OSFS.h:230:9: note: 'OSFS::result OSFS::readNBytesChk(uint16_t, unsigned int, void*)' declared here, later in the translation unit

  result readNBytesChk(uint16_t address, unsigned int num, void* input);

         ^

sketch\OSFS.h: In instantiation of 'OSFS::result OSFS::getFile(const char*, T&) [with T = _LeOS_STAT_EEPROM]':

sketch\LeOS_EEPROM.cpp:367:39:   required from here

sketch\OSFS.h:121:23: warning: 'readNBytesChk' was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]

   return readNBytesChk(add, size, &buf);

                       ^

sketch\OSFS.h:230:9: note: 'OSFS::result OSFS::readNBytesChk(uint16_t, unsigned int, void*)' declared here, later in the translation unit

  result readNBytesChk(uint16_t address, unsigned int num, void* input);

         ^`

**Comment by asjdf** [comment]
same problem .........

**Comment by charlesbaynham** [comment]
Hi both, sorry I missed this thread when it was opened. I'll take a look

**Comment by asjdf** [comment]
My chip is esp8266. This problem was solved after I updated my development board library.

**Comment by charlesbaynham** [comment]
Great. Do you know what version you were using when you were seeing this error? Also, @NickNifontov , what chip are you building for?

**Comment by NickNifontov** [comment]
Arduino Pro Mini
Arduino 1.8.6
Arduino beta 1.9.x

**Comment by charlesbaynham** [comment]
I think this should be sorted now with 90ace2c704e015abaa0ea54fbf59611488af4ce4. Could you try compiling and running the updated examples?
