### ISSUE TITLE
Not working with Blue Pill | stm32duino

### ISSUE THREAD

**Issue by jarusRnD** [charlesbaynham/OSFS#10]
First i uploaded > writeTest example
Serial output below given
`Overly Simplified File System (OSFS) : write-test
Formatting device...
Storing an integer...
Storing a string
Storing a complex data type
Done
`

then uploaded > readTest example 
Serial output below given

`Overly Simplified File System (OSFS) : read-test
Looking for testInt...
Error: 5
Looking for testStr...
Error: 5
Looking for complex data type...
Error: 5
Done`

**Comment by charlesbaynham** [comment]
Hi @jarus0, thanks for the bug report. 

The error codes are defined here:

https://github.com/charlesbaynham/OSFS/blob/8dc2795e46d5c18e16416c8aaa862801b42c445b/src/OSFS.h#L67-L77

So error 5 means "UNFORMATTED". 

It sounds like the write test is failing to write to EEPROM. I've never used the Blue Pill, but this page implies that it doesn't have any EEPROM:

![image](https://user-images.githubusercontent.com/4397637/90624809-76e08080-e210-11ea-8bf0-a160de7f94f9.png)

If that's true than that'd be the problem I'm afraid.

**Comment by charlesbaynham** [comment]
I'm going to close this issue now, but do reopen it if I've got it wrong
